name: cubby

services:
  api:
    build:
      context: .
      dockerfile: api.dockerfile
      # network: host
      args:
        - DB_HOST=${DB_HOST}
        - DB_PORT=${DB_PORT}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_NAME=${DB_NAME}
        - API_LISTEN_ADDR=${API_LISTEN_ADDR}
        - STYTCH_PROJECT_ID=${STYTCH_PROJECT_ID}
        - STYTCH_SECRET=${STYTCH_SECRET}
        - COOKIE_DOMAIN=${COOKIE_DOMAIN}
        - PUBLIC_CORS_URL=${PUBLIC_CORS_URL}
        - PUBLIC_WEB_URL=${PUBLIC_WEB_URL}
    # ports:
    #   - '${API_LISTEN_ADDR}:${API_LISTEN_ADDR}'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${API_LISTEN_ADDR}/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    # labels:
    #   - 'traefik.http.services.api.loadbalancer.server.port=7002'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - API_LISTEN_ADDR=${API_LISTEN_ADDR}
      - STYTCH_PROJECT_ID=${STYTCH_PROJECT_ID}
      - STYTCH_SECRET=${STYTCH_SECRET}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - PUBLIC_CORS_URL=${PUBLIC_CORS_URL}
      - PUBLIC_WEB_URL=${PUBLIC_WEB_URL}
  web:
    build:
      context: .
      dockerfile: web.dockerfile
      args:
        - PUBLIC_API_URL=${PUBLIC_API_URL}
        - PUBLIC_WEB_URL=${PUBLIC_WEB_URL}
    # ports:
    #   - '3000:3000'
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    environment:
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_WEB_URL=${PUBLIC_WEB_URL}
